# route:
#     receiver: 'slack'
#
# receivers:
#     - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             username: '<username>'
#             channel: '#<channel-name>'
#             api_url: '<incomming-webhook-url>'
#     - name: "alerta"
#        webhook_configs:
#            - url: 'http://alerta/api/webhooks/prometheus'
#              send_resolved: true
route:
  routes:
  - receiver: "alertsnitch"
    continue: true
  - receiver: "slack"
  group_by: ['alertname']
  group_wait:      15s
  group_interval:  15s
  repeat_interval: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

receivers:
- name: "alertsnitch"
  webhook_configs:
  - url: http://alertsnitch:9567/webhook
    send_resolved: true
- name: "slack"
  slack_configs:
  - channel: '#montd-observability'
    send_resolved: true
