version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}
    promalert_data: {}

networks:
  front-tier:
  back-tier:

services:

  prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 42004:9090
    depends_on:
      - cadvisor
    links:
      - alertmanager:alertmanager
    networks:
      - back-tier
    restart: always
    
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 42088:8080
    networks:
      - back-tier
    restart: always
  
  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports:
      - 42006:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana:7.5.5
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 42003:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

  loki:
    image: grafana/loki:1.6.0
    ports:
      - "42002:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - back-tier 

  promtail:
    image: grafana/promtail:1.6.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - back-tier
